# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumname', models.CharField(max_length=100)),
                ('relase_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MusicGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genrename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MusicSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songname', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=200)),
                ('musicalbum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MusicAlbum')),
            ],
        ),
        migrations.AddField(
            model_name='musicalbum',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MusicGenre'),
        ),
    ]
