# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalbum',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='musicgenre',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='musicsong',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
